---
title: "Presentaci칩n"
format: revealjs
editor: visual
---

## 游꿢 Objetivos de la reuni칩n

- Presentaci칩n del proyecto.
- Validar entregables del proyecto.
- Evaluar recursos disponibles.
- Armar plan de trabajo.


## Presentaci칩n del proyecto

Plataforma tecnol칩gica para gestionar ciclo de MyE con trazabilidad, seguridad y tiempos de respuesta adecuados a la toma de decisiones.

## Productos entregables

- Plan de Monitoreo (y Evaluaci칩n?).
- Plataforma tecnol칩gica de soporte del Plan.

## Plan

- Teor칤a del cambio. 
- Preguntas de evaluaci칩n.
- Matriz de Indicadores.
  - Definici칩n
  - Forma de c치lculo.
  - Fuente de informaci칩n base.
  - Dimensiones relevantes (geogr치fica, g칠nero, innovaci칩n, sectores, exportaciones).


## Plataforma tecnol칩gica

- Es una herramienta para responder las preguntas plateadas en el plan.
- Automatiza procesos.
- Data Lake -> Data Warehouse -> Tableros, Reportes.

## Recursos 

- Usuarios del sistema.
  - 쯈ui칠nes son? 쯈u칠 necesidades tienen?
- Infraestructura inform치tica.
- Fuentes de informaci칩n.
  - Internas (archivos Excel, Word, Papel, Otros Sistemas de Informaci칩n).
  - Externas (쮻GI?, 쯀NE?).

## Plan de Trabajo

- Revisi칩n documentaci칩n.
- Revisi칩n recursos disponibles.
- Inventario de fuentes de informaci칩n.



## Taller Breve

- Preguntas de para responder con el sistema.
  - 쮺u치ntos son los costos operativos del programa?
  - 쮺u치nto es el costo por peso de inversi칩n promovido?
  - 쮺u치ntos proyectos promovimos?
  - 쮺u치nto demoran los proyectos en aprobarse?
  - 쮺u치ntos puestos de trabajo promovemos?
  - 쮺u치ntos puestos de trabajo crea el r칠gimen?

## Dimensiones relevantes

- Geogr치fica (departamento, municipio).
- Temporal.
- G칠nero
- Sector de la econom칤a

## Matriz de indicadores

- Clasificar indicadores de recursos, actividades, productos, resultados, impactos.

<!-- - Clasificar criterios de evaluabilidad: -->
<!--   - Eficacia -->
<!--   - Sostenibilidad -->
<!--   - Eficiencia -->
<!--   - Coherencia -->
<!--   - Impacto -->
  


